// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * ScrapeConfig defines a namespaced Prometheus scrape_config to be aggregated across
 * multiple namespaces into the Prometheus configuration.
 */
export class ScrapeConfig extends pulumi.CustomResource {
    /**
     * Get an existing ScrapeConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ScrapeConfig {
        return new ScrapeConfig(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:monitoring.coreos.com/v1alpha1:ScrapeConfig';

    /**
     * Returns true if the given object is an instance of ScrapeConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ScrapeConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ScrapeConfig.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"monitoring.coreos.com/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"ScrapeConfig" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * spec defines the specification of ScrapeConfigSpec.
     */
    public readonly spec!: pulumi.Output<outputs.monitoring.v1alpha1.ScrapeConfigSpec>;
    /**
     * status defines the status subresource. It is under active development and is updated only when the
     * "StatusForConfigurationResources" feature gate is enabled.
     *
     * Most recent observed status of the ScrapeConfig. Read-only.
     * More info:
     * https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    public readonly status!: pulumi.Output<outputs.monitoring.v1alpha1.ScrapeConfigStatus | undefined>;

    /**
     * Create a ScrapeConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ScrapeConfigArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "monitoring.coreos.com/v1alpha1";
            resourceInputs["kind"] = "ScrapeConfig";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.monitoring.v1alpha1.scrapeConfigSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ScrapeConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ScrapeConfig resource.
 */
export interface ScrapeConfigArgs {
    apiVersion?: pulumi.Input<"monitoring.coreos.com/v1alpha1">;
    kind?: pulumi.Input<"ScrapeConfig">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * spec defines the specification of ScrapeConfigSpec.
     */
    spec?: pulumi.Input<inputs.monitoring.v1alpha1.ScrapeConfigSpecArgs>;
    /**
     * status defines the status subresource. It is under active development and is updated only when the
     * "StatusForConfigurationResources" feature gate is enabled.
     *
     * Most recent observed status of the ScrapeConfig. Read-only.
     * More info:
     * https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    status?: pulumi.Input<inputs.monitoring.v1alpha1.ScrapeConfigStatusArgs>;
}
