// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * The `PrometheusRule` custom resource definition (CRD) defines [alerting](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) and [recording](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) rules to be evaluated by `Prometheus` or `ThanosRuler` objects.
 *
 * `Prometheus` and `ThanosRuler` objects select `PrometheusRule` objects using label and namespace selectors.
 */
export class PrometheusRule extends pulumi.CustomResource {
    /**
     * Get an existing PrometheusRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PrometheusRule {
        return new PrometheusRule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:monitoring.coreos.com/v1:PrometheusRule';

    /**
     * Returns true if the given object is an instance of PrometheusRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PrometheusRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PrometheusRule.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"monitoring.coreos.com/v1" | undefined>;
    public readonly kind!: pulumi.Output<"PrometheusRule" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * spec defines the specification of desired alerting rule definitions for Prometheus.
     */
    public readonly spec!: pulumi.Output<outputs.monitoring.v1.PrometheusRuleSpec>;
    /**
     * status defines the status subresource. It is under active development and is updated only when the
     * "StatusForConfigurationResources" feature gate is enabled.
     *
     * Most recent observed status of the PrometheusRule. Read-only.
     * More info:
     * https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    public readonly status!: pulumi.Output<outputs.monitoring.v1.PrometheusRuleStatus | undefined>;

    /**
     * Create a PrometheusRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PrometheusRuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "monitoring.coreos.com/v1";
            resourceInputs["kind"] = "PrometheusRule";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PrometheusRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PrometheusRule resource.
 */
export interface PrometheusRuleArgs {
    apiVersion?: pulumi.Input<"monitoring.coreos.com/v1">;
    kind?: pulumi.Input<"PrometheusRule">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * spec defines the specification of desired alerting rule definitions for Prometheus.
     */
    spec?: pulumi.Input<inputs.monitoring.v1.PrometheusRuleSpecArgs>;
    /**
     * status defines the status subresource. It is under active development and is updated only when the
     * "StatusForConfigurationResources" feature gate is enabled.
     *
     * Most recent observed status of the PrometheusRule. Read-only.
     * More info:
     * https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    status?: pulumi.Input<inputs.monitoring.v1.PrometheusRuleStatusArgs>;
}
